import { describe, expect, it } from "vitest";
import { AUDIT_TOPICS, buildAuditVisualData, gradeToScore, inferAuditTopic, parseAuditBody } from "@/lib/audit-visual";

const body = `Grade: D-\n\nRed flags\n- We track location and share private data.\n- You grant a perpetual license to your content.\n\nWorth noting\n- We retain deleted files in backups.\n\nReasonable\n- Cancel anytime.\n- Two-factor authentication is available.\n\nVerdict: Careful.`;

describe("audit visual model", () => {
  it("parses all three sections with stable semantics", () => { const result = parseAuditBody(body); expect(result.grade).toBe("D-"); expect(result.clauses.map((clause) => clause.kind)).toEqual(["red-flag", "red-flag", "worth-noting", "reasonable", "reasonable"]); expect(result.clauses.map((clause) => clause.severity)).toEqual([3, 3, 2, 0, 0]); expect(parseAuditBody(body).clauses).toEqual(result.clauses) });
  it("handles missing sections and unknown grades", () => { expect(parseAuditBody("A narrative only.")).toEqual({ grade: "—", clauses: [] }); expect(gradeToScore("unknown")).toBe(0) });
  it("normalizes grades", () => { expect(["A", "B", "C", "D", "F"].map(gradeToScore)).toEqual([95, 85, 75, 65, 45]); expect(gradeToScore("C-")).toBe(72); expect(gradeToScore("B+")).toBe(88) });
  it("infers representative topics", () => { expect(inferAuditTopic("personalized advertising tracks private data")).toBe("Privacy"); expect(inferAuditTopic("perpetual license to sublicense your content")).toBe("Ownership"); expect(inferAuditTopic("binding arbitration and jury waiver")).toBe("Legal"); expect(inferAuditTopic("non-refundable recurring subscription fee")).toBe("Billing") });
  it("uses fixed topic order, aggregation, counts, and accessible prose", () => { const result = buildAuditVisualData(body); expect(result.topics.map((topic) => topic.topic)).toEqual(AUDIT_TOPICS); expect(result.counts).toEqual({ "red-flag": 2, "worth-noting": 1, reasonable: 2 }); expect(result.description).toContain("Grade D-: two high-risk clauses"); expect(result.description).toContain("two reasonable clauses") });
  it("compacts long lists into a deterministic eighth aggregate", () => { const long = `Grade: F\n\nRed flags\n${Array.from({ length: 12 }, (_, index) => `- Private data clause ${index}`).join("\n")}`; const result = buildAuditVisualData(long); expect(result.clauses).toHaveLength(8); expect(result.clauses[7]).toMatchObject({ id: "overflow", overflowCount: 5, severity: 3, topic: "Privacy" }); expect(result.counts["red-flag"]).toBe(12) });
  it("accepts complete version-one metadata", () => { const metadata = { audit: { version: 1, grade: "A", clauses: [{ id: "clear", label: "Clear refund policy", kind: "reasonable", severity: 0, topic: "Billing" }] } }; const result = buildAuditVisualData(body, metadata); expect(result.grade).toBe("A"); expect(result.clauses).toHaveLength(1); expect(result.clauses[0].id).toBe("clear") });
  it("falls back when metadata is incomplete or invalid", () => { const invalid = { audit: { version: 1, grade: "A", clauses: [{ label: "No topic", kind: "reasonable", severity: 0 }] } }; expect(buildAuditVisualData(body, invalid).grade).toBe("D-"); expect(buildAuditVisualData(body, { audit: { version: 2, clauses: [] } }).clauses).toHaveLength(5) });
});
